import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "../../components/authService";
import WebSocketProvider from "../../components/wsService";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col md:flex-row h-full min-h-screen font-sans`}>
        <AuthContextProvider>
          <WebSocketProvider>
            {children}
          </WebSocketProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}

